/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkDialogs.xs. Do not edit this file, edit GtkDialogs.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkDialogs.xs"
#include "gtkmodule.h"

#line 13 "GtkDialogs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "GtkDialogs.c"

XS(XS_Pidgin__Dialogs_destroy_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_destroy_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_dialogs_destroy_all();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_about); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_about)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_dialogs_about();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_im); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_im)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_dialogs_im();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_im_with_user); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_im_with_user)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "account, username");
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	username = (const char *)SvPV_nolen(ST(1));

	pidgin_dialogs_im_with_user(account, username);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_dialogs_info();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_log); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_log)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_dialogs_log();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_alias_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_alias_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "contact");
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));

	pidgin_dialogs_alias_contact(contact);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_alias_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_alias_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "buddy");
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));

	pidgin_dialogs_alias_buddy(buddy);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_alias_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_alias_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));

	pidgin_dialogs_alias_chat(chat);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_remove_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_remove_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "buddy");
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));

	pidgin_dialogs_remove_buddy(buddy);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_remove_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_remove_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "group");
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));

	pidgin_dialogs_remove_group(group);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_remove_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_remove_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));

	pidgin_dialogs_remove_chat(chat);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Dialogs_remove_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Dialogs_remove_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "contact");
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));

	pidgin_dialogs_remove_contact(contact);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__Dialogs); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__Dialogs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::Dialogs::destroy_all", XS_Pidgin__Dialogs_destroy_all, file, "");
        newXSproto("Pidgin::Dialogs::about", XS_Pidgin__Dialogs_about, file, "");
        newXSproto("Pidgin::Dialogs::im", XS_Pidgin__Dialogs_im, file, "");
        newXSproto("Pidgin::Dialogs::im_with_user", XS_Pidgin__Dialogs_im_with_user, file, "$$");
        newXSproto("Pidgin::Dialogs::info", XS_Pidgin__Dialogs_info, file, "");
        newXSproto("Pidgin::Dialogs::log", XS_Pidgin__Dialogs_log, file, "");
        newXSproto("Pidgin::Dialogs::alias_contact", XS_Pidgin__Dialogs_alias_contact, file, "$");
        newXSproto("Pidgin::Dialogs::alias_buddy", XS_Pidgin__Dialogs_alias_buddy, file, "$");
        newXSproto("Pidgin::Dialogs::alias_chat", XS_Pidgin__Dialogs_alias_chat, file, "$");
        newXSproto("Pidgin::Dialogs::remove_buddy", XS_Pidgin__Dialogs_remove_buddy, file, "$");
        newXSproto("Pidgin::Dialogs::remove_group", XS_Pidgin__Dialogs_remove_group, file, "$");
        newXSproto("Pidgin::Dialogs::remove_chat", XS_Pidgin__Dialogs_remove_chat, file, "$");
        newXSproto("Pidgin::Dialogs::remove_contact", XS_Pidgin__Dialogs_remove_contact, file, "$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

