/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkFt.xs. Do not edit this file, edit GtkFt.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkFt.xs"
#include "gtkmodule.h"

#line 13 "GtkFt.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "GtkFt.c"

XS(XS_Pidgin__Xfer_set_xfer_dialog); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer_set_xfer_dialog)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));

	pidgin_set_xfer_dialog(dialog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer_get_xfer_dialog); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer_get_xfer_dialog)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Pidgin__Xfer__Dialog	RETVAL;

	RETVAL = pidgin_get_xfer_dialog();
	ST(0) = purple_perl_bless_object(RETVAL, "Pidgin::Xfer::Dialog");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Pidgin__Xfer__Dialog_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	Pidgin__Xfer__Dialog	RETVAL;

	RETVAL = pidgin_xfer_dialog_new(/* void */);
	ST(0) = purple_perl_bless_object(RETVAL, "Pidgin::Xfer::Dialog");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Pidgin__Xfer__Dialog_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));

	pidgin_xfer_dialog_destroy(dialog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 0 || items > 1)
       croak_xs_usage(cv,  "dialog = NULL");
    {
	Pidgin__Xfer__Dialog	dialog;

	if (items < 1)
	    dialog = NULL;
	else {
	    dialog = purple_perl_ref_object(ST(0));
	}

	pidgin_xfer_dialog_show(dialog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_hide); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_hide)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));

	pidgin_xfer_dialog_hide(dialog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_add_xfer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_add_xfer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1));

	pidgin_xfer_dialog_add_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_remove_xfer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_remove_xfer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1));

	pidgin_xfer_dialog_remove_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_cancel_xfer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_cancel_xfer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1));

	pidgin_xfer_dialog_cancel_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Xfer__Dialog_update_xfer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Xfer__Dialog_update_xfer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0));
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1));

	pidgin_xfer_dialog_update_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__Xfer); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__Xfer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::Xfer::set_xfer_dialog", XS_Pidgin__Xfer_set_xfer_dialog, file, "$");
        newXSproto("Pidgin::Xfer::get_xfer_dialog", XS_Pidgin__Xfer_get_xfer_dialog, file, "");
        newXSproto("Pidgin::Xfer::Dialog::new", XS_Pidgin__Xfer__Dialog_new, file, "$");
        newXSproto("Pidgin::Xfer::Dialog::destroy", XS_Pidgin__Xfer__Dialog_destroy, file, "$");
        newXSproto("Pidgin::Xfer::Dialog::show", XS_Pidgin__Xfer__Dialog_show, file, ";$");
        newXSproto("Pidgin::Xfer::Dialog::hide", XS_Pidgin__Xfer__Dialog_hide, file, "$");
        newXSproto("Pidgin::Xfer::Dialog::add_xfer", XS_Pidgin__Xfer__Dialog_add_xfer, file, "$$");
        newXSproto("Pidgin::Xfer::Dialog::remove_xfer", XS_Pidgin__Xfer__Dialog_remove_xfer, file, "$$");
        newXSproto("Pidgin::Xfer::Dialog::cancel_xfer", XS_Pidgin__Xfer__Dialog_cancel_xfer, file, "$$");
        newXSproto("Pidgin::Xfer::Dialog::update_xfer", XS_Pidgin__Xfer__Dialog_update_xfer, file, "$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

