/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkIMHtmlToolbar.xs. Do not edit this file, edit GtkIMHtmlToolbar.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkIMHtmlToolbar.xs"
#include "gtkmodule.h"

/* This can't work at the moment since I don't have a typemap for Gtk::Widget.
 * I thought about using the one from libgtk2-perl but wasn't sure how to go
 * about doing that.

Gtk::Widget
gtk_imhtmltoolbar_new()

void
gtk_imhtmltoolbar_attach(toolbar, imhtml)
	Pidgin::IMHtmlToolbar toolbar
	Gtk::Widget imhtml
*/

#line 26 "GtkIMHtmlToolbar.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 69 "GtkIMHtmlToolbar.c"

XS(XS_Pidgin__IMHtmlToolbar_associate_smileys); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__IMHtmlToolbar_associate_smileys)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "toolbar, proto_id");
    {
	Pidgin__IMHtmlToolbar	toolbar = purple_perl_ref_object(ST(0));
	const char *	proto_id = (const char *)SvPV_nolen(ST(1));

	gtk_imhtmltoolbar_associate_smileys(toolbar, proto_id);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__IMHtmlToolbar); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__IMHtmlToolbar)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::IMHtmlToolbar::associate_smileys", XS_Pidgin__IMHtmlToolbar_associate_smileys, file, "$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

