/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkLog.xs. Do not edit this file, edit GtkLog.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkLog.xs"
#include "gtkmodule.h"

#line 13 "GtkLog.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "GtkLog.c"

XS(XS_Pidgin__Log_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Log_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = pidgin_log_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Pidgin__Log_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Log_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "type, buddyname, account");
    {
	Purple__LogType	type = (Purple__LogType)SvIV(ST(0));
	const char *	buddyname = (const char *)SvPV_nolen(ST(1));
	Purple__Account	account = purple_perl_ref_object(ST(2));

	pidgin_log_show(type, buddyname, account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Log_show_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Log_show_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "contact");
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));

	pidgin_log_show_contact(contact);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__SysLog_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__SysLog_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_syslog_show();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__Log); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__Log)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::Log::get_handle", XS_Pidgin__Log_get_handle, file, "");
        newXSproto("Pidgin::Log::show", XS_Pidgin__Log_show, file, "$$$");
        newXSproto("Pidgin::Log::show_contact", XS_Pidgin__Log_show_contact, file, "$");
        newXSproto("Pidgin::SysLog::show", XS_Pidgin__SysLog_show, file, "");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

