/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkPounce.xs. Do not edit this file, edit GtkPounce.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkPounce.xs"
#include "gtkmodule.h"

#line 13 "GtkPounce.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "GtkPounce.c"

XS(XS_Pidgin__Pounce_editor_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Pounce_editor_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "account, name, cur_pounce");
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__Pounce	cur_pounce = purple_perl_ref_object(ST(2));

	pidgin_pounce_editor_show(account, name, cur_pounce);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Pounces_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Pounces_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = pidgin_pounces_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Pidgin__Pounces__Manager_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Pounces__Manager_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_pounces_manager_show();
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__Pounces__Manager_hide); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__Pounces__Manager_hide)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	pidgin_pounces_manager_hide();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__Pounce); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__Pounce)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::Pounce::editor_show", XS_Pidgin__Pounce_editor_show, file, "$$$");
        newXSproto("Pidgin::Pounces::get_handle", XS_Pidgin__Pounces_get_handle, file, "");
        newXSproto("Pidgin::Pounces::Manager::show", XS_Pidgin__Pounces__Manager_show, file, "");
        newXSproto("Pidgin::Pounces::Manager::hide", XS_Pidgin__Pounces__Manager_hide, file, "");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

