/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of GtkStatusBox.xs. Do not edit this file, edit GtkStatusBox.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "GtkStatusBox.xs"
#include "gtkmodule.h"

/* This can't work at the moment since I don't have a typemap for Gtk::Widget.
 * I thought about using the one from libgtk2-perl but wasn't sure how to go
 * about doing that.
Gtk::Widget
pidgin_status_box_new()

Gtk::Widget
pidgin_status_box_new_with_account(account)
	Purple::Account account

void
pidgin_status_box_add(status_box, type, pixbuf, text, sec_text, data)
	Pidgin::StatusBox status_box
	Pidgin::StatusBox::ItemType type
	GdkPixbuf pixbuf
	const char * text
	const char * sec_text
	gpointer data
*/

#line 33 "GtkStatusBox.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 76 "GtkStatusBox.c"

XS(XS_Pidgin__StatusBox_add_separator); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__StatusBox_add_separator)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0));

	pidgin_status_box_add_separator(status_box);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__StatusBox_set_connecting); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__StatusBox_set_connecting)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "status_box, connecting");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0));
	gboolean	connecting = (bool)SvTRUE(ST(1));

	pidgin_status_box_set_connecting(status_box, connecting);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__StatusBox_pulse_connecting); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__StatusBox_pulse_connecting)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0));

	pidgin_status_box_pulse_connecting(status_box);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__StatusBox_set_buddy_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__StatusBox_set_buddy_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "status_box, img");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0));
	Purple__StoredImage	img = purple_perl_ref_object(ST(1));

	pidgin_status_box_set_buddy_icon(status_box, img);
    }
    XSRETURN_EMPTY;
}


XS(XS_Pidgin__StatusBox_get_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Pidgin__StatusBox_get_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0));
	gchar_own *	RETVAL;

	RETVAL = pidgin_status_box_get_message(status_box);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);

    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin__StatusBox); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin__StatusBox)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Pidgin::StatusBox::add_separator", XS_Pidgin__StatusBox_add_separator, file, "$");
        newXSproto("Pidgin::StatusBox::set_connecting", XS_Pidgin__StatusBox_set_connecting, file, "$$");
        newXSproto("Pidgin::StatusBox::pulse_connecting", XS_Pidgin__StatusBox_pulse_connecting, file, "$");
        newXSproto("Pidgin::StatusBox::set_buddy_icon", XS_Pidgin__StatusBox_set_buddy_icon, file, "$$");
        newXSproto("Pidgin::StatusBox::get_message", XS_Pidgin__StatusBox_get_message, file, "$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

