/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Pidgin.xs. Do not edit this file, edit Pidgin.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Pidgin.xs"
#define PIDGIN_PERL_BOOT_PROTO(x) \
	void boot_Pidgin__##x(pTHX_ CV *cv)

#define PIDGIN_PERL_BOOT(x) \
	purple_perl_callXS(boot_Pidgin__##x, cv, mark)

#include "gtkmodule.h"

/* Prototypes for the BOOT section below. */
PIDGIN_PERL_BOOT_PROTO(Account);
PIDGIN_PERL_BOOT_PROTO(BuddyList);
PIDGIN_PERL_BOOT_PROTO(Connection);
PIDGIN_PERL_BOOT_PROTO(Conversation);
PIDGIN_PERL_BOOT_PROTO(Conversation__Window);
PIDGIN_PERL_BOOT_PROTO(Debug);
PIDGIN_PERL_BOOT_PROTO(Dialogs);
PIDGIN_PERL_BOOT_PROTO(IMHtml);
PIDGIN_PERL_BOOT_PROTO(IMHtmlToolbar);
PIDGIN_PERL_BOOT_PROTO(Log);
PIDGIN_PERL_BOOT_PROTO(MenuTray);
PIDGIN_PERL_BOOT_PROTO(Plugin);
PIDGIN_PERL_BOOT_PROTO(PluginPref);
PIDGIN_PERL_BOOT_PROTO(Pounce);
PIDGIN_PERL_BOOT_PROTO(Prefs);
PIDGIN_PERL_BOOT_PROTO(Privacy);
PIDGIN_PERL_BOOT_PROTO(Roomlist);
PIDGIN_PERL_BOOT_PROTO(Status);
#ifndef _WIN32
PIDGIN_PERL_BOOT_PROTO(Session);
#endif
PIDGIN_PERL_BOOT_PROTO(Sound);
PIDGIN_PERL_BOOT_PROTO(StatusBox);
PIDGIN_PERL_BOOT_PROTO(Themes);
PIDGIN_PERL_BOOT_PROTO(Utils);
PIDGIN_PERL_BOOT_PROTO(Xfer);

#line 47 "Pidgin.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 90 "Pidgin.c"
#ifdef __cplusplus
extern "C"
#endif
XS(boot_Pidgin); /* prototype to pass -Wmissing-prototypes */
XS(boot_Pidgin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;


    /* Initialisation Section */

#line 41 "Pidgin.xs"
	PIDGIN_PERL_BOOT(Account);
	PIDGIN_PERL_BOOT(BuddyList);
	PIDGIN_PERL_BOOT(Connection);
	PIDGIN_PERL_BOOT(Conversation);
	PIDGIN_PERL_BOOT(Conversation__Window);
	PIDGIN_PERL_BOOT(Debug);
	PIDGIN_PERL_BOOT(Dialogs);
	PIDGIN_PERL_BOOT(IMHtml);
	PIDGIN_PERL_BOOT(IMHtmlToolbar);
	PIDGIN_PERL_BOOT(Log);
	PIDGIN_PERL_BOOT(MenuTray);
	PIDGIN_PERL_BOOT(Plugin);
	PIDGIN_PERL_BOOT(PluginPref);
	PIDGIN_PERL_BOOT(Pounce);
	PIDGIN_PERL_BOOT(Prefs);
	PIDGIN_PERL_BOOT(Privacy);
	PIDGIN_PERL_BOOT(Roomlist);
	PIDGIN_PERL_BOOT(Status);
#ifndef _WIN32
	PIDGIN_PERL_BOOT(Session);
#endif
	PIDGIN_PERL_BOOT(Sound);
	PIDGIN_PERL_BOOT(StatusBox);
	PIDGIN_PERL_BOOT(Themes);
	PIDGIN_PERL_BOOT(Utils);
	PIDGIN_PERL_BOOT(Xfer);

#line 138 "Pidgin.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

