/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Conversation.xs. Do not edit this file, edit Conversation.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Conversation.xs"
#include "module.h"

#line 13 "Conversation.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "Conversation.c"

XS(XS_Purple_get_ims); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple_get_ims)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 97 "Conversation.xs"
	GList *l;
#line 73 "Conversation.c"
#line 99 "Conversation.xs"
	for (l = purple_get_ims(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 78 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple_get_conversations); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple_get_conversations)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 106 "Conversation.xs"
	GList *l;
#line 100 "Conversation.c"
#line 108 "Conversation.xs"
	for (l = purple_get_conversations(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 105 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple_get_chats); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple_get_chats)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 115 "Conversation.xs"
	GList *l;
#line 127 "Conversation.c"
#line 117 "Conversation.xs"
	for (l = purple_get_chats(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 132 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversations_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversations_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_conversations_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));

	purple_conversation_destroy(conv);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_get_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__ConversationType	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_type(conv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__Account	RETVAL;

	RETVAL = purple_conversation_get_account(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_gc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_gc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__Connection	RETVAL;

	RETVAL = purple_conversation_get_gc(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Connection");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_set_title); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_set_title)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, title");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	title = (const char *)SvPV_nolen(ST(1));

	purple_conversation_set_title(conv, title);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_get_title); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_title)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_title(conv);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_autoset_title); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_autoset_title)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));

	purple_conversation_autoset_title(conv);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_set_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_set_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, name");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_conversation_set_name(conv, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_name(conv);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_set_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_set_logging)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, log");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	gboolean	log = (bool)SvTRUE(ST(1));

	purple_conversation_set_logging(conv, log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_is_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_is_logging)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_conversation_is_logging(conv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_im_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_im_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__Conversation__IM	RETVAL;

	RETVAL = purple_conversation_get_im_data(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::IM");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_chat_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_chat_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__Conversation__Chat	RETVAL;

	RETVAL = purple_conversation_get_chat_data(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::Chat");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, key");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	gpointer	RETVAL;

	RETVAL = purple_conversation_get_data(conv, key);
	ST(0) = purple_perl_bless_object(RETVAL, "gpointer");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_get_features); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_get_features)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__ConnectionFlags	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_features(conv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_has_focus); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_has_focus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_conversation_has_focus(conv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_update); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_update)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, type");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__ConvUpdateType	type = (Purple__ConvUpdateType)SvIV(ST(1));

	purple_conversation_update(conv, type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "class, type, account, name");
    {
	Purple__ConversationType	type = (Purple__ConversationType)SvIV(ST(1));
	Purple__Account	account = purple_perl_ref_object(ST(2));
	const char *	name = (const char *)SvPV_nolen(ST(3));
	Purple__Conversation	RETVAL;

	RETVAL = purple_conversation_new(type, account, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_set_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_set_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, account");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));

	purple_conversation_set_account(conv, account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_write); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_write)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "conv, who, message, flags, mtime");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	who = (const char *)SvPV_nolen(ST(1));
	const char *	message = (const char *)SvPV_nolen(ST(2));
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3));
	time_t	mtime = (time_t)SvIV(ST(4));

	purple_conversation_write(conv, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_do_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_do_command)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "conv, cmdline, markup, error");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	cmdline = (const char *)SvPV_nolen(ST(1));
	const char *	markup = (const char *)SvPV_nolen(ST(2));
	char **	error = INT2PTR(char **,SvIV(ST(3)));
	gboolean	RETVAL;

	RETVAL = purple_conversation_do_command(conv, cmdline, markup, error);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_get_conversation); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_conversation)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	Purple__Conversation	RETVAL;

	RETVAL = purple_conv_im_get_conversation(im);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_set_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_set_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "im, icon");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	Purple__Buddy__Icon	icon = purple_perl_ref_object(ST(1));

	purple_conv_im_set_icon(im, icon);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_get_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	Purple__Buddy__Icon	RETVAL;

	RETVAL = purple_conv_im_get_icon(im);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Buddy::Icon");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_set_typing_state); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_set_typing_state)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "im, state");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	Purple__TypingState	state = (Purple__TypingState)SvIV(ST(1));

	purple_conv_im_set_typing_state(im, state);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_get_typing_state); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_typing_state)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	Purple__TypingState	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_typing_state(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_start_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_start_typing_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "im, timeout");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	int	timeout = (int)SvIV(ST(1));

	purple_conv_im_start_typing_timeout(im, timeout);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_stop_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_stop_typing_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));

	purple_conv_im_stop_typing_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_get_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_typing_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	guint	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_typing_timeout(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_set_type_again); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_set_type_again)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "im, val");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	time_t	val = (time_t)SvIV(ST(1));

	purple_conv_im_set_type_again(im, val);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_get_type_again); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_type_again)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	time_t	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_type_again(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_start_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_start_send_typed_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));

	purple_conv_im_start_send_typed_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_stop_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_stop_send_typed_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));

	purple_conv_im_stop_send_typed_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_get_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_get_send_typed_timeout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	guint	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_send_typed_timeout(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__IM_update_typing); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_update_typing)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));

	purple_conv_im_update_typing(im);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_send); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_send)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "im, message");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	const char *	message = (const char *)SvPV_nolen(ST(1));

	purple_conv_im_send(im, message);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__IM_write); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__IM_write)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "im, who, message, flags, mtime");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0));
	const char *	who = (const char *)SvPV_nolen(ST(1));
	const char *	message = (const char *)SvPV_nolen(ST(2));
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3));
	time_t	mtime = (time_t)SvIV(ST(4));

	purple_conv_im_write(im, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation_present_error); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_present_error)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "who, account, what");
    {
	const char *	who = (const char *)SvPV_nolen(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	const char *	what = (const char *)SvPV_nolen(ST(2));
	gboolean	RETVAL;

	RETVAL = purple_conv_present_error(who, account, what);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation_custom_smiley_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation_custom_smiley_close)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "conv, smile");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0));
	const char *	smile = (const char *)SvPV_nolen(ST(1));

	purple_conv_custom_smiley_close(conv, smile);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_get_conversation); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_conversation)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	Purple__Conversation	RETVAL;

	RETVAL = purple_conv_chat_get_conversation(chat);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_set_users); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_set_users)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, users");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	SV *	users = ST(1);
#line 333 "Conversation.xs"
	GList *l, *t_GL;
	int i, t_len;
#line 1038 "Conversation.c"
#line 336 "Conversation.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(users));

	for (i = 0; i <= t_len; i++)
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(users), i, 0)));

	for (l = purple_conv_chat_set_users(chat, t_GL); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1049 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversation__Chat_get_users); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_users)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
#line 350 "Conversation.xs"
	GList *l;
#line 1072 "Conversation.c"
#line 352 "Conversation.xs"
	for (l = purple_conv_chat_get_users(chat); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1077 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversation__Chat_ignore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_ignore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_conv_chat_ignore(chat, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_unignore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_unignore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_conv_chat_unignore(chat, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_set_ignored); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_set_ignored)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, ignored");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	SV *	ignored = ST(1);
#line 371 "Conversation.xs"
	GList *l, *t_GL;
	int i, t_len;
#line 1142 "Conversation.c"
#line 374 "Conversation.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(ignored));

	for (i = 0; i <= t_len; i++)
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(ignored), i, 0)));

	for (l = purple_conv_chat_set_ignored(chat, t_GL); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1153 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversation__Chat_get_ignored); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_ignored)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
#line 388 "Conversation.xs"
	GList *l;
#line 1176 "Conversation.c"
#line 390 "Conversation.xs"
	for (l = purple_conv_chat_get_ignored(chat); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1181 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversation__Chat_get_topic); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_topic)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_topic(chat);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_set_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_set_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, id");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	int	id = (int)SvIV(ST(1));

	purple_conv_chat_set_id(chat, id);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_get_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_id(chat);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_send); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_send)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, message");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	message = (const char *)SvPV_nolen(ST(1));

	purple_conv_chat_send(chat, message);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_write); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_write)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "chat, who, message, flags, mtime");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	who = (const char *)SvPV_nolen(ST(1));
	const char *	message = (const char *)SvPV_nolen(ST(2));
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3));
	time_t	mtime = (time_t)SvIV(ST(4));

	purple_conv_chat_write(chat, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_add_users); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_add_users)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "chat, users, extra_msgs, flags, new_arrivals");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	SV *	users = ST(1);
	SV *	extra_msgs = ST(2);
	SV *	flags = ST(3);
	gboolean	new_arrivals = (bool)SvTRUE(ST(4));
#line 428 "Conversation.xs"
	GList *t_GL_users, *t_GL_extra_msgs, *t_GL_flags;
	int i, t_len;
#line 1316 "Conversation.c"
#line 431 "Conversation.xs"
	t_GL_users = NULL;
	t_len = av_len((AV *)SvRV(users));

	for (i = 0; i <= t_len; i++)
		t_GL_users = g_list_append(t_GL_users, SvPVutf8_nolen(*av_fetch((AV *)SvRV(users), i, 0)));

	t_GL_flags = NULL;
	t_len = av_len((AV *)SvRV(flags));

	for (i = 0; i <= t_len; i++)
		t_GL_flags = g_list_append(t_GL_flags, SvPVutf8_nolen(*av_fetch((AV *)SvRV(flags), i, 0)));

	t_GL_extra_msgs = NULL;
	t_len = av_len((AV *)SvRV(extra_msgs));

	for (i = 0; i <= t_len; i++)
		t_GL_extra_msgs = g_list_append(t_GL_extra_msgs, SvPVutf8_nolen(*av_fetch((AV *)SvRV(extra_msgs), i, 0)));

	purple_conv_chat_add_users(chat, t_GL_users, t_GL_extra_msgs, t_GL_flags, new_arrivals);

	g_list_free(t_GL_users);
	g_list_free(t_GL_extra_msgs);
	g_list_free(t_GL_flags);
#line 1341 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Conversation__Chat_find_user); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_find_user)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, user");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	user = (const char *)SvPV_nolen(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_conv_chat_find_user(chat, user);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_clear_users); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_clear_users)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));

	purple_conv_chat_clear_users(chat);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_set_nick); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_set_nick)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, nick");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	nick = (const char *)SvPV_nolen(ST(1));

	purple_conv_chat_set_nick(chat, nick);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_get_nick); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_get_nick)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_nick(chat);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_purple_find_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_purple_find_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "gc, id");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	int	id = (int)SvIV(ST(1));
	Purple__Conversation	RETVAL;

	RETVAL = purple_find_chat(gc, id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_left); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_left)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));

	purple_conv_chat_left(chat);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Conversation__Chat_has_left); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_has_left)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_conv_chat_has_left(chat);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_cb_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_cb_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__Conversation__ChatBuddy	RETVAL;

	RETVAL = purple_conv_chat_cb_find(chat, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::ChatBuddy");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_cb_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_cb_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "cb");
    {
	Purple__Conversation__ChatBuddy	cb = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_cb_get_name(cb);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Conversation__Chat_cb_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Conversation__Chat_cb_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "cb");
    {
	Purple__Conversation__ChatBuddy	cb = purple_perl_ref_object(ST(0));

	purple_conv_chat_cb_destroy(cb);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Conversation); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Conversation)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::get_ims", XS_Purple_get_ims, file, "");
        newXSproto("Purple::get_conversations", XS_Purple_get_conversations, file, "");
        newXSproto("Purple::get_chats", XS_Purple_get_chats, file, "");
        newXSproto("Purple::Conversations::get_handle", XS_Purple__Conversations_get_handle, file, "");
        newXSproto("Purple::Conversation::destroy", XS_Purple__Conversation_destroy, file, "$");
        newXSproto("Purple::Conversation::get_type", XS_Purple__Conversation_get_type, file, "$");
        newXSproto("Purple::Conversation::get_account", XS_Purple__Conversation_get_account, file, "$");
        newXSproto("Purple::Conversation::get_gc", XS_Purple__Conversation_get_gc, file, "$");
        newXSproto("Purple::Conversation::set_title", XS_Purple__Conversation_set_title, file, "$$");
        newXSproto("Purple::Conversation::get_title", XS_Purple__Conversation_get_title, file, "$");
        newXSproto("Purple::Conversation::autoset_title", XS_Purple__Conversation_autoset_title, file, "$");
        newXSproto("Purple::Conversation::set_name", XS_Purple__Conversation_set_name, file, "$$");
        newXSproto("Purple::Conversation::get_name", XS_Purple__Conversation_get_name, file, "$");
        newXSproto("Purple::Conversation::set_logging", XS_Purple__Conversation_set_logging, file, "$$");
        newXSproto("Purple::Conversation::is_logging", XS_Purple__Conversation_is_logging, file, "$");
        newXSproto("Purple::Conversation::get_im_data", XS_Purple__Conversation_get_im_data, file, "$");
        newXSproto("Purple::Conversation::get_chat_data", XS_Purple__Conversation_get_chat_data, file, "$");
        newXSproto("Purple::Conversation::get_data", XS_Purple__Conversation_get_data, file, "$$");
        newXSproto("Purple::Conversation::get_features", XS_Purple__Conversation_get_features, file, "$");
        newXSproto("Purple::Conversation::has_focus", XS_Purple__Conversation_has_focus, file, "$");
        newXSproto("Purple::Conversation::update", XS_Purple__Conversation_update, file, "$$");
        newXSproto("Purple::Conversation::new", XS_Purple__Conversation_new, file, "$$$$");
        newXSproto("Purple::Conversation::set_account", XS_Purple__Conversation_set_account, file, "$$");
        newXSproto("Purple::Conversation::write", XS_Purple__Conversation_write, file, "$$$$$");
        newXSproto("Purple::Conversation::do_command", XS_Purple__Conversation_do_command, file, "$$$$");
        newXSproto("Purple::Conversation::IM::get_conversation", XS_Purple__Conversation__IM_get_conversation, file, "$");
        newXSproto("Purple::Conversation::IM::set_icon", XS_Purple__Conversation__IM_set_icon, file, "$$");
        newXSproto("Purple::Conversation::IM::get_icon", XS_Purple__Conversation__IM_get_icon, file, "$");
        newXSproto("Purple::Conversation::IM::set_typing_state", XS_Purple__Conversation__IM_set_typing_state, file, "$$");
        newXSproto("Purple::Conversation::IM::get_typing_state", XS_Purple__Conversation__IM_get_typing_state, file, "$");
        newXSproto("Purple::Conversation::IM::start_typing_timeout", XS_Purple__Conversation__IM_start_typing_timeout, file, "$$");
        newXSproto("Purple::Conversation::IM::stop_typing_timeout", XS_Purple__Conversation__IM_stop_typing_timeout, file, "$");
        newXSproto("Purple::Conversation::IM::get_typing_timeout", XS_Purple__Conversation__IM_get_typing_timeout, file, "$");
        newXSproto("Purple::Conversation::IM::set_type_again", XS_Purple__Conversation__IM_set_type_again, file, "$$");
        newXSproto("Purple::Conversation::IM::get_type_again", XS_Purple__Conversation__IM_get_type_again, file, "$");
        newXSproto("Purple::Conversation::IM::start_send_typed_timeout", XS_Purple__Conversation__IM_start_send_typed_timeout, file, "$");
        newXSproto("Purple::Conversation::IM::stop_send_typed_timeout", XS_Purple__Conversation__IM_stop_send_typed_timeout, file, "$");
        newXSproto("Purple::Conversation::IM::get_send_typed_timeout", XS_Purple__Conversation__IM_get_send_typed_timeout, file, "$");
        newXSproto("Purple::Conversation::IM::update_typing", XS_Purple__Conversation__IM_update_typing, file, "$");
        newXSproto("Purple::Conversation::IM::send", XS_Purple__Conversation__IM_send, file, "$$");
        newXSproto("Purple::Conversation::IM::write", XS_Purple__Conversation__IM_write, file, "$$$$$");
        newXSproto("Purple::Conversation::present_error", XS_Purple__Conversation_present_error, file, "$$$");
        newXSproto("Purple::Conversation::custom_smiley_close", XS_Purple__Conversation_custom_smiley_close, file, "$$");
        newXSproto("Purple::Conversation::Chat::get_conversation", XS_Purple__Conversation__Chat_get_conversation, file, "$");
        newXSproto("Purple::Conversation::Chat::set_users", XS_Purple__Conversation__Chat_set_users, file, "$$");
        newXSproto("Purple::Conversation::Chat::get_users", XS_Purple__Conversation__Chat_get_users, file, "$");
        newXSproto("Purple::Conversation::Chat::ignore", XS_Purple__Conversation__Chat_ignore, file, "$$");
        newXSproto("Purple::Conversation::Chat::unignore", XS_Purple__Conversation__Chat_unignore, file, "$$");
        newXSproto("Purple::Conversation::Chat::set_ignored", XS_Purple__Conversation__Chat_set_ignored, file, "$$");
        newXSproto("Purple::Conversation::Chat::get_ignored", XS_Purple__Conversation__Chat_get_ignored, file, "$");
        newXSproto("Purple::Conversation::Chat::get_topic", XS_Purple__Conversation__Chat_get_topic, file, "$");
        newXSproto("Purple::Conversation::Chat::set_id", XS_Purple__Conversation__Chat_set_id, file, "$$");
        newXSproto("Purple::Conversation::Chat::get_id", XS_Purple__Conversation__Chat_get_id, file, "$");
        newXSproto("Purple::Conversation::Chat::send", XS_Purple__Conversation__Chat_send, file, "$$");
        newXSproto("Purple::Conversation::Chat::write", XS_Purple__Conversation__Chat_write, file, "$$$$$");
        newXSproto("Purple::Conversation::Chat::add_users", XS_Purple__Conversation__Chat_add_users, file, "$$$$$");
        newXSproto("Purple::Conversation::Chat::find_user", XS_Purple__Conversation__Chat_find_user, file, "$$");
        newXSproto("Purple::Conversation::Chat::clear_users", XS_Purple__Conversation__Chat_clear_users, file, "$");
        newXSproto("Purple::Conversation::Chat::set_nick", XS_Purple__Conversation__Chat_set_nick, file, "$$");
        newXSproto("Purple::Conversation::Chat::get_nick", XS_Purple__Conversation__Chat_get_nick, file, "$");
        newXSproto("Purple::Conversation::Chat::purple_find_chat", XS_Purple__Conversation__Chat_purple_find_chat, file, "$$");
        newXSproto("Purple::Conversation::Chat::left", XS_Purple__Conversation__Chat_left, file, "$");
        newXSproto("Purple::Conversation::Chat::has_left", XS_Purple__Conversation__Chat_has_left, file, "$");
        newXSproto("Purple::Conversation::Chat::cb_find", XS_Purple__Conversation__Chat_cb_find, file, "$$");
        newXSproto("Purple::Conversation::Chat::cb_get_name", XS_Purple__Conversation__Chat_cb_get_name, file, "$");
        newXSproto("Purple::Conversation::Chat::cb_destroy", XS_Purple__Conversation__Chat_cb_destroy, file, "$");

    /* Initialisation Section */

#line 7 "Conversation.xs"
{
	HV *type_stash = gv_stashpv("Purple::Conversation::Type", 1);
	HV *update_stash = gv_stashpv("Purple::Conversation::Update::Type", 1);
	HV *typing_stash = gv_stashpv("Purple::Conversation::TypingState", 1);
	HV *flags_stash = gv_stashpv("Purple::Conversation::Flags", 1);
	HV *cbflags_stash = gv_stashpv("Purple::Conversation::ChatBuddy::Flags", 1);

	static const constiv *civ, type_const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_CONV_TYPE_##name}
		const_iv(UNKNOWN),
		const_iv(IM),
		const_iv(CHAT),
		const_iv(MISC),
		const_iv(ANY),
	};
	static const constiv update_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_CONV_UPDATE_##name}
		const_iv(ADD),
		const_iv(REMOVE),
		const_iv(ACCOUNT),
		const_iv(TYPING),
		const_iv(UNSEEN),
		const_iv(LOGGING),
		const_iv(TOPIC),
/*
		const_iv(ONLINE),
		const_iv(OFFLINE),
*/
		const_iv(AWAY),
		const_iv(ICON),
		const_iv(TITLE),
		const_iv(CHATLEFT),
		const_iv(FEATURES),
	};
	static const constiv typing_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_##name}
		const_iv(NOT_TYPING),
		const_iv(TYPING),
		const_iv(TYPED),
	};
	static const constiv flags_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_MESSAGE_##name}
		const_iv(SEND),
		const_iv(RECV),
		const_iv(SYSTEM),
		const_iv(AUTO_RESP),
		const_iv(ACTIVE_ONLY),
		const_iv(NICK),
		const_iv(NO_LOG),
		const_iv(WHISPER),
		const_iv(ERROR),
		const_iv(DELAYED),
		const_iv(RAW),
		const_iv(IMAGES),
		const_iv(NOTIFY),
		const_iv(NO_LINKIFY),
	};
	static const constiv cbflags_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_CBFLAGS_##name}
		const_iv(NONE),
		const_iv(VOICE),
		const_iv(HALFOP),
		const_iv(OP),
		const_iv(FOUNDER),
		const_iv(TYPING),
	};

	for (civ = type_const_iv + sizeof(type_const_iv) / sizeof(type_const_iv[0]); civ-- > type_const_iv; )
		newCONSTSUB(type_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = update_const_iv + sizeof(update_const_iv) / sizeof(update_const_iv[0]); civ-- > update_const_iv; )
		newCONSTSUB(update_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = typing_const_iv + sizeof(typing_const_iv) / sizeof(typing_const_iv[0]); civ-- > typing_const_iv; )
		newCONSTSUB(typing_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = flags_const_iv + sizeof(flags_const_iv) / sizeof(flags_const_iv[0]); civ-- > flags_const_iv; )
		newCONSTSUB(flags_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = cbflags_const_iv + sizeof(cbflags_const_iv) / sizeof(cbflags_const_iv[0]); civ-- > cbflags_const_iv; )
		newCONSTSUB(cbflags_stash, (char *)civ->name, newSViv(civ->iv));
}

#line 1735 "Conversation.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

