/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Debug.xs. Do not edit this file, edit Debug.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Debug.xs"
#include "module.h"

#line 13 "Debug.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "Debug.c"

XS(XS_Purple__Debug_purple_debug); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_purple_debug)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "level, category, string");
    {
	Purple__DebugLevel	level = (Purple__DebugLevel)SvIV(ST(0));
	const char *	category = (const char *)SvPV_nolen(ST(1));
	const char *	string = (const char *)SvPV_nolen(ST(2));
#line 30 "Debug.xs"
	purple_debug(level, category, "%s", string);
#line 74 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_misc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_misc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0));
	const char *	string = (const char *)SvPV_nolen(ST(1));
#line 37 "Debug.xs"
	purple_debug_misc(category, "%s", string);
#line 95 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0));
	const char *	string = (const char *)SvPV_nolen(ST(1));
#line 44 "Debug.xs"
	purple_debug_info(category, "%s", string);
#line 116 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_warning); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_warning)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0));
	const char *	string = (const char *)SvPV_nolen(ST(1));
#line 51 "Debug.xs"
	purple_debug_warning(category, "%s", string);
#line 137 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_error); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_error)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0));
	const char *	string = (const char *)SvPV_nolen(ST(1));
#line 58 "Debug.xs"
	purple_debug_error(category, "%s", string);
#line 158 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_fatal); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_fatal)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0));
	const char *	string = (const char *)SvPV_nolen(ST(1));
#line 65 "Debug.xs"
	purple_debug_fatal(category, "%s", string);
#line 179 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_set_enabled); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_set_enabled)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "enabled");
    {
	gboolean	enabled = (bool)SvTRUE(ST(0));

	purple_debug_set_enabled(enabled);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Debug_is_enabled); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Debug_is_enabled)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	gboolean	RETVAL;

	RETVAL = purple_debug_is_enabled();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Debug); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Debug)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Debug::purple_debug", XS_Purple__Debug_purple_debug, file, "$$$");
        newXSproto("Purple::Debug::misc", XS_Purple__Debug_misc, file, "$$");
        newXSproto("Purple::Debug::info", XS_Purple__Debug_info, file, "$$");
        newXSproto("Purple::Debug::warning", XS_Purple__Debug_warning, file, "$$");
        newXSproto("Purple::Debug::error", XS_Purple__Debug_error, file, "$$");
        newXSproto("Purple::Debug::fatal", XS_Purple__Debug_fatal, file, "$$");
        newXSproto("Purple::Debug::set_enabled", XS_Purple__Debug_set_enabled, file, "$");
        newXSproto("Purple::Debug::is_enabled", XS_Purple__Debug_is_enabled, file, "");

    /* Initialisation Section */

#line 7 "Debug.xs"
{
	HV *stash = gv_stashpv("Purple::Debug", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_DEBUG_##name}
		const_iv(ALL),
		const_iv(MISC),
		const_iv(INFO),
		const_iv(WARNING),
		const_iv(ERROR),
		const_iv(FATAL),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 270 "Debug.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

