/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of ImgStore.xs. Do not edit this file, edit ImgStore.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "ImgStore.xs"
#include "module.h"

#line 13 "ImgStore.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "ImgStore.c"

XS(XS_Purple__ImgStore_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "data, size, filename");
    {
	void *	data = INT2PTR(void *,SvIV(ST(0)));
	size_t	size = (size_t)SvUV(ST(1));
	const char *	filename = (const char *)SvPV_nolen(ST(2));
	Purple__StoredImage	RETVAL;

	RETVAL = purple_imgstore_add(data, size, filename);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_add_with_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_add_with_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "data, size, filename");
    {
	void *	data = INT2PTR(void *,SvIV(ST(0)));
	size_t	size = (size_t)SvUV(ST(1));
	const char *	filename = (const char *)SvPV_nolen(ST(2));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_imgstore_add_with_id(data, size, filename);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_find_by_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_find_by_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	int	id = (int)SvIV(ST(0));
	Purple__StoredImage	RETVAL;

	RETVAL = purple_imgstore_find_by_id(id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_get_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_get_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	Purple__StoredImage	i = purple_perl_ref_object(ST(0));
	gconstpointer	RETVAL;
	dXSTARG;

	RETVAL = purple_imgstore_get_data(i);
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_get_filename); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_get_filename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	Purple__StoredImage	i = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_imgstore_get_filename(i);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_get_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_get_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	Purple__StoredImage	i = purple_perl_ref_object(ST(0));
	size_t	RETVAL;
	dXSTARG;

	RETVAL = purple_imgstore_get_size(i);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_get_extension); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_get_extension)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	Purple__StoredImage	i = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_imgstore_get_extension(i);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_ref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_ref)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	Purple__StoredImage	id = purple_perl_ref_object(ST(0));
	Purple__StoredImage	RETVAL;

	RETVAL = purple_imgstore_ref(id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_unref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_unref)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	Purple__StoredImage	id = purple_perl_ref_object(ST(0));
	Purple__StoredImage	RETVAL;

	RETVAL = purple_imgstore_unref(id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ImgStore_ref_by_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_ref_by_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	int	id = (int)SvIV(ST(0));

	purple_imgstore_ref_by_id(id);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ImgStore_unref_by_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ImgStore_unref_by_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	int	id = (int)SvIV(ST(0));

	purple_imgstore_unref_by_id(id);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__ImgStore); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__ImgStore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::ImgStore::add", XS_Purple__ImgStore_add, file, "$$$");
        newXSproto("Purple::ImgStore::add_with_id", XS_Purple__ImgStore_add_with_id, file, "$$$");
        newXSproto("Purple::ImgStore::find_by_id", XS_Purple__ImgStore_find_by_id, file, "$");
        newXSproto("Purple::ImgStore::get_data", XS_Purple__ImgStore_get_data, file, "$");
        newXSproto("Purple::ImgStore::get_filename", XS_Purple__ImgStore_get_filename, file, "$");
        newXSproto("Purple::ImgStore::get_size", XS_Purple__ImgStore_get_size, file, "$");
        newXSproto("Purple::ImgStore::get_extension", XS_Purple__ImgStore_get_extension, file, "$");
        newXSproto("Purple::ImgStore::ref", XS_Purple__ImgStore_ref, file, "$");
        newXSproto("Purple::ImgStore::unref", XS_Purple__ImgStore_unref, file, "$");
        newXSproto("Purple::ImgStore::ref_by_id", XS_Purple__ImgStore_ref_by_id, file, "$");
        newXSproto("Purple::ImgStore::unref_by_id", XS_Purple__ImgStore_unref_by_id, file, "$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

