/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Network.xs. Do not edit this file, edit Network.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Network.xs"
#include "module.h"

#line 13 "Network.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "Network.c"

XS(XS_Purple__Network_get_local_system_ip); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_get_local_system_ip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_network_get_local_system_ip(fd);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_get_my_ip); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_get_my_ip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_network_get_my_ip(fd);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_get_port_from_fd); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_get_port_from_fd)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0));
	unsigned short	RETVAL;
	dXSTARG;

	RETVAL = purple_network_get_port_from_fd(fd);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_get_public_ip); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_get_public_ip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_network_get_public_ip();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_ip_atoi); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_ip_atoi)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ip");
    {
	const char *	ip = (const char *)SvPV_nolen(ST(0));
	const unsigned char *	RETVAL;
	dXSTARG;

	RETVAL = purple_network_ip_atoi(ip);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_listen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_listen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "port, socket_type, cb, cb_data");
    {
	unsigned short	port = (unsigned short)SvUV(ST(0));
	int	socket_type = (int)SvIV(ST(1));
	Purple__NetworkListenCallback	cb = INT2PTR(Purple__NetworkListenCallback,SvIV(ST(2)));
	gpointer	cb_data = purple_perl_ref_object(ST(3));
	Purple__NetworkListenData	RETVAL;

	RETVAL = purple_network_listen(port, socket_type, cb, cb_data);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::NetworkListenData");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_listen_range); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_listen_range)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "start, end, socket_type, cb, cb_data");
    {
	unsigned short	start = (unsigned short)SvUV(ST(0));
	unsigned short	end = (unsigned short)SvUV(ST(1));
	int	socket_type = (int)SvIV(ST(2));
	Purple__NetworkListenCallback	cb = INT2PTR(Purple__NetworkListenCallback,SvIV(ST(3)));
	gpointer	cb_data = purple_perl_ref_object(ST(4));
	Purple__NetworkListenData	RETVAL;

	RETVAL = purple_network_listen_range(start, end, socket_type, cb, cb_data);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::NetworkListenData");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Network_set_public_ip); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Network_set_public_ip)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ip");
    {
	const char *	ip = (const char *)SvPV_nolen(ST(0));

	purple_network_set_public_ip(ip);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Network); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Network)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Network::get_local_system_ip", XS_Purple__Network_get_local_system_ip, file, "$");
        newXSproto("Purple::Network::get_my_ip", XS_Purple__Network_get_my_ip, file, "$");
        newXSproto("Purple::Network::get_port_from_fd", XS_Purple__Network_get_port_from_fd, file, "$");
        newXSproto("Purple::Network::get_public_ip", XS_Purple__Network_get_public_ip, file, "");
        newXSproto("Purple::Network::ip_atoi", XS_Purple__Network_ip_atoi, file, "$");
        newXSproto("Purple::Network::listen", XS_Purple__Network_listen, file, "$$$$");
        newXSproto("Purple::Network::listen_range", XS_Purple__Network_listen_range, file, "$$$$$");
        newXSproto("Purple::Network::set_public_ip", XS_Purple__Network_set_public_ip, file, "$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

