/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Proxy.xs. Do not edit this file, edit Proxy.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Proxy.xs"
#include "module.h"

#line 13 "Proxy.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "Proxy.c"

XS(XS_Purple__Proxy_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Proxy_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_proxy_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));

	purple_proxy_info_destroy(info);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ProxyInfo_get_host); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_get_host)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_host(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_get_password); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_get_password)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_password(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_get_port); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_get_port)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_port(info);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_get_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_get_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	Purple__ProxyType	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_type(info);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_get_username); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_get_username)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_username(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__ProxyInfo	RETVAL;

	RETVAL = purple_proxy_info_new();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::ProxyInfo");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__ProxyInfo_set_host); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_set_host)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "info, host");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	host = (const char *)SvPV_nolen(ST(1));

	purple_proxy_info_set_host(info, host);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ProxyInfo_set_password); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_set_password)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "info, password");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	password = (const char *)SvPV_nolen(ST(1));

	purple_proxy_info_set_password(info, password);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ProxyInfo_set_port); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_set_port)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "info, port");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	int	port = (int)SvIV(ST(1));

	purple_proxy_info_set_port(info, port);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ProxyInfo_set_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_set_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "info, type");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	Purple__ProxyType	type = (Purple__ProxyType)SvIV(ST(1));

	purple_proxy_info_set_type(info, type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__ProxyInfo_set_username); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__ProxyInfo_set_username)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "info, username");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0));
	const char *	username = (const char *)SvPV_nolen(ST(1));

	purple_proxy_info_set_username(info, username);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Proxy_global_proxy_get_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Proxy_global_proxy_get_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__ProxyInfo	RETVAL;

	RETVAL = purple_global_proxy_get_info();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::ProxyInfo");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Proxy); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Proxy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Proxy::get_handle", XS_Purple__Proxy_get_handle, file, "");
        newXSproto("Purple::ProxyInfo::destroy", XS_Purple__ProxyInfo_destroy, file, "$");
        newXSproto("Purple::ProxyInfo::get_host", XS_Purple__ProxyInfo_get_host, file, "$");
        newXSproto("Purple::ProxyInfo::get_password", XS_Purple__ProxyInfo_get_password, file, "$");
        newXSproto("Purple::ProxyInfo::get_port", XS_Purple__ProxyInfo_get_port, file, "$");
        newXSproto("Purple::ProxyInfo::get_type", XS_Purple__ProxyInfo_get_type, file, "$");
        newXSproto("Purple::ProxyInfo::get_username", XS_Purple__ProxyInfo_get_username, file, "$");
        newXSproto("Purple::ProxyInfo::new", XS_Purple__ProxyInfo_new, file, "");
        newXSproto("Purple::ProxyInfo::set_host", XS_Purple__ProxyInfo_set_host, file, "$$");
        newXSproto("Purple::ProxyInfo::set_password", XS_Purple__ProxyInfo_set_password, file, "$$");
        newXSproto("Purple::ProxyInfo::set_port", XS_Purple__ProxyInfo_set_port, file, "$$");
        newXSproto("Purple::ProxyInfo::set_type", XS_Purple__ProxyInfo_set_type, file, "$$");
        newXSproto("Purple::ProxyInfo::set_username", XS_Purple__ProxyInfo_set_username, file, "$$");
        newXSproto("Purple::Proxy::global_proxy_get_info", XS_Purple__Proxy_global_proxy_get_info, file, "");

    /* Initialisation Section */

#line 7 "Proxy.xs"
{
	HV *stash = gv_stashpv("Purple::ProxyType", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_PROXY_##name}
		const_iv(USE_GLOBAL),
		const_iv(NONE),
		const_iv(HTTP),
		const_iv(SOCKS4),
		const_iv(SOCKS5),
		const_iv(USE_ENVVAR),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 404 "Proxy.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

