/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Signal.xs. Do not edit this file, edit Signal.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Signal.xs"
#include "module.h"
#include "../perl-handlers.h"

#line 14 "Signal.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 57 "Signal.c"

XS(XS_Purple__Signal_connect_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_connect_priority)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 5 || items > 6)
       croak_xs_usage(cv,  "instance, signal, plugin, callback, priority, data = 0");
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
	SV *	callback = ST(3);
	int	priority = (int)SvIV(ST(4));
	SV *	data;

	if (items < 6)
	    data = 0;
	else {
	    data = ST(5);
	}
#line 16 "Signal.xs"
	purple_perl_signal_connect(plugin, instance, signal, callback, data, priority);
#line 84 "Signal.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Signal_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_connect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 4 || items > 5)
       croak_xs_usage(cv,  "instance, signal, plugin, callback, data = 0");
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
	SV *	callback = ST(3);
	SV *	data;

	if (items < 5)
	    data = 0;
	else {
	    data = ST(4);
	}
#line 26 "Signal.xs"
	purple_perl_signal_connect(plugin, instance, signal, callback, data, PURPLE_SIGNAL_PRIORITY_DEFAULT);
#line 114 "Signal.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Signal_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_disconnect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "instance, signal, plugin");
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
#line 34 "Signal.xs"
	purple_perl_signal_disconnect(plugin, instance, signal);
#line 136 "Signal.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Signal); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Signal)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Signal::connect_priority", XS_Purple__Signal_connect_priority, file, "$$$$$;$");
        newXSproto("Purple::Signal::connect", XS_Purple__Signal_connect, file, "$$$$;$");
        newXSproto("Purple::Signal::disconnect", XS_Purple__Signal_disconnect, file, "$$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

