/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Smiley.xs. Do not edit this file, edit Smiley.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Smiley.xs"
#include "module.h"

#line 13 "Smiley.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 56 "Smiley.c"

XS(XS_Purple__Smiley_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "img, shortcut");
    {
	Purple__StoredImage	img = purple_perl_ref_object(ST(0));
	const char *	shortcut = (const char *)SvPV_nolen(ST(1));
	Purple__Smiley	RETVAL;

	RETVAL = purple_smiley_new(img, shortcut);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_new_from_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_new_from_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "shortcut, filepath");
    {
	const char *	shortcut = (const char *)SvPV_nolen(ST(0));
	const char *	filepath = (const char *)SvPV_nolen(ST(1));
	Purple__Smiley	RETVAL;

	RETVAL = purple_smiley_new_from_file(shortcut, filepath);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_delete); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_delete)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));

	purple_smiley_delete(smiley);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Smiley_set_shortcut); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_set_shortcut)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "smiley, shortcut");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	const char *	shortcut = (const char *)SvPV_nolen(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_smiley_set_shortcut(smiley, shortcut);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_set_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_set_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "smiley, data, data_len");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	guchar *	data = (guchar *)SvPV_nolen(ST(1));
	size_t	data_len = (size_t)SvUV(ST(2));

	purple_smiley_set_data(smiley, data, data_len);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Smiley_get_shortcut); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_shortcut)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_shortcut(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_get_checksum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_checksum)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_checksum(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_get_stored_image); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_stored_image)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	Purple__StoredImage	RETVAL;

	RETVAL = purple_smiley_get_stored_image(smiley);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_get_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "smiley, len");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	size_t *	len = INT2PTR(size_t *,SvIV(ST(1)));
	gconstpointer	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_data(smiley, len);
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_get_extension); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_extension)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_extension(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Smiley_get_full_path); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smiley_get_full_path)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0));
	gchar_own *	RETVAL;

	RETVAL = purple_smiley_get_full_path(smiley);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);

    }
    XSRETURN(1);
}


XS(XS_Purple__Smileys_get_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smileys_get_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 64 "Smiley.xs"
    GList *l;
#line 324 "Smiley.c"
#line 66 "Smiley.xs"
    for (l = purple_smileys_get_all(); l != NULL; l = g_list_delete_link(l, l)) {
        XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Smiley")));
    }
#line 329 "Smiley.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Smileys_find_by_shortcut); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smileys_find_by_shortcut)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "shortcut");
    {
	const char *	shortcut = (const char *)SvPV_nolen(ST(0));
	Purple__Smiley	RETVAL;

	RETVAL = purple_smileys_find_by_shortcut(shortcut);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smileys_find_by_checksum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smileys_find_by_checksum)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "checksum");
    {
	const char *	checksum = (const char *)SvPV_nolen(ST(0));
	Purple__Smiley	RETVAL;

	RETVAL = purple_smileys_find_by_checksum(checksum);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Smileys_get_storing_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Smileys_get_storing_dir)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smileys_get_storing_dir();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Smiley); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Smiley)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Smiley::new", XS_Purple__Smiley_new, file, "$$");
        newXSproto("Purple::Smiley::new_from_file", XS_Purple__Smiley_new_from_file, file, "$$");
        newXSproto("Purple::Smiley::delete", XS_Purple__Smiley_delete, file, "$");
        newXSproto("Purple::Smiley::set_shortcut", XS_Purple__Smiley_set_shortcut, file, "$$");
        newXSproto("Purple::Smiley::set_data", XS_Purple__Smiley_set_data, file, "$$$");
        newXSproto("Purple::Smiley::get_shortcut", XS_Purple__Smiley_get_shortcut, file, "$");
        newXSproto("Purple::Smiley::get_checksum", XS_Purple__Smiley_get_checksum, file, "$");
        newXSproto("Purple::Smiley::get_stored_image", XS_Purple__Smiley_get_stored_image, file, "$");
        newXSproto("Purple::Smiley::get_data", XS_Purple__Smiley_get_data, file, "$$");
        newXSproto("Purple::Smiley::get_extension", XS_Purple__Smiley_get_extension, file, "$");
        newXSproto("Purple::Smiley::get_full_path", XS_Purple__Smiley_get_full_path, file, "$");
        newXSproto("Purple::Smileys::get_all", XS_Purple__Smileys_get_all, file, "");
        newXSproto("Purple::Smileys::find_by_shortcut", XS_Purple__Smileys_find_by_shortcut, file, "$");
        newXSproto("Purple::Smileys::find_by_checksum", XS_Purple__Smileys_find_by_checksum, file, "$");
        newXSproto("Purple::Smileys::get_storing_dir", XS_Purple__Smileys_get_storing_dir, file, "");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

